In [1]:
from astropy.io import fits
import numpy as np
import matplotlib.pyplot as plt


In [2]:
fpath = "2pt_y3dv_y6_ggl_maglim_mdet_nolssw__2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate_nosourcesreals_sompzmean_jan25_BLINDED.fits"
ffile = fits.open(fpath)

In [5]:
ffile.info()

Filename: 2pt_y3dv_y6_ggl_maglim_mdet_nolssw__2pt_NG_final_2ptunblind_02_26_21_wnz_maglim_covupdate_nosourcesreals_sompzmean_jan25_BLINDED.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()      
  1  COVMAT        1 ImageHDU        17   (1000, 1000)   float64   
  2  xip           1 BinTableHDU     39   200R x 8C   [K, K, K, D, D, D, D, D]   
  3  xim           1 BinTableHDU     39   200R x 8C   [K, K, K, D, D, D, D, D]   
  4  gammat        1 BinTableHDU     37   480R x 7C   [K, K, K, D, D, D, D]   
  5  wtheta        1 BinTableHDU     39   120R x 8C   [K, K, K, D, D, D, D, D]   
  6  nz_source     1 BinTableHDU     32   300R x 7C   [D, D, D, D, D, D, D]   
  7  nz_lens       1 BinTableHDU     34   150R x 9C   [D, D, D, D, D, D, D, D, D]   


In [11]:
xip_data = ffile[2].data

In [20]:
xip_data.columns

ColDefs(
    name = 'BIN1'; format = 'K'
    name = 'BIN2'; format = 'K'
    name = 'ANGBIN'; format = 'K'
    name = 'VALUE'; format = 'D'
    name = 'ANGLEMIN'; format = 'D'; unit = 'arcmin'
    name = 'ANGLEMAX'; format = 'D'; unit = 'arcmin'
    name = 'ANG'; format = 'D'; unit = 'arcmin'
    name = 'NPAIRS'; format = 'D'
)

In [15]:
xip_data['BIN1']

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4], dtype='>i8')

In [16]:
xip_data['BIN2']

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4], dtype='>i8')

In [19]:
xip_data['ANGBIN']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='>i8')

In [21]:
xip_data['VALUE']

array([3.39719726e-05, 3.23800838e-05, 1.96258389e-05, 1.98302953e-05,
       8.16009800e-06, 7.65081733e-06, 7.81902696e-06, 5.43705132e-06,
       4.89359756e-06, 3.61680669e-06, 1.77947592e-06, 2.35545370e-06,
       1.75801559e-06, 1.40395329e-06, 1.37013784e-06, 6.63898711e-07,
       4.36223413e-07, 5.31596554e-07, 4.59684892e-07, 2.28876082e-07,
       4.41544642e-05, 3.63139186e-05, 3.03291589e-05, 2.68075290e-05,
       1.48003505e-05, 1.60896204e-05, 1.23429527e-05, 8.37533563e-06,
       8.09256849e-06, 6.55740734e-06, 5.71694116e-06, 3.39940443e-06,
       2.95468927e-06, 1.97909043e-06, 1.69526872e-06, 1.18374853e-06,
       1.01364197e-06, 8.07736254e-07, 4.20372121e-07, 2.55801199e-07,
       4.73439504e-05, 5.18545246e-05, 3.84101602e-05, 2.77628765e-05,
       2.41244938e-05, 2.37579326e-05, 1.62188515e-05, 1.07951690e-05,
       1.05816935e-05, 7.59096026e-06, 6.61573471e-06, 4.60041692e-06,
       4.10805160e-06, 2.87237402e-06, 2.26299875e-06, 1.53133434e-06,
      

In [23]:
xip_data['ANGLEMIN']

array([  2.5       ,   3.14731353,   3.96223298,   4.98815579,
         6.27971608,   7.90569415,   9.95267926,  12.52968084,
        15.77393361,  19.85820587,  25.        ,  31.47313529,
        39.62232981,  49.88155787,  62.79716079,  79.0569415 ,
        99.52679264, 125.29680841, 157.73933612, 198.58205868,
         2.5       ,   3.14731353,   3.96223298,   4.98815579,
         6.27971608,   7.90569415,   9.95267926,  12.52968084,
        15.77393361,  19.85820587,  25.        ,  31.47313529,
        39.62232981,  49.88155787,  62.79716079,  79.0569415 ,
        99.52679264, 125.29680841, 157.73933612, 198.58205868,
         2.5       ,   3.14731353,   3.96223298,   4.98815579,
         6.27971608,   7.90569415,   9.95267926,  12.52968084,
        15.77393361,  19.85820587,  25.        ,  31.47313529,
        39.62232981,  49.88155787,  62.79716079,  79.0569415 ,
        99.52679264, 125.29680841, 157.73933612, 198.58205868,
         2.5       ,   3.14731353,   3.96223298,   4.98

In [24]:
xip_data['ANGLEMAX']

array([  3.14731353,   3.96223298,   4.98815579,   6.27971608,
         7.90569415,   9.95267926,  12.52968084,  15.77393361,
        19.85820587,  25.        ,  31.47313529,  39.62232981,
        49.88155787,  62.79716079,  79.0569415 ,  99.52679264,
       125.29680841, 157.73933612, 198.58205868, 250.        ,
         3.14731353,   3.96223298,   4.98815579,   6.27971608,
         7.90569415,   9.95267926,  12.52968084,  15.77393361,
        19.85820587,  25.        ,  31.47313529,  39.62232981,
        49.88155787,  62.79716079,  79.0569415 ,  99.52679264,
       125.29680841, 157.73933612, 198.58205868, 250.        ,
         3.14731353,   3.96223298,   4.98815579,   6.27971608,
         7.90569415,   9.95267926,  12.52968084,  15.77393361,
        19.85820587,  25.        ,  31.47313529,  39.62232981,
        49.88155787,  62.79716079,  79.0569415 ,  99.52679264,
       125.29680841, 157.73933612, 198.58205868, 250.        ,
         3.14731353,   3.96223298,   4.98815579,   6.27

In [25]:
xip_data['ANG']

array([  2.8290551 ,   3.56172569,   4.48403221,   5.64521982,
         7.10706514,   8.9477756 ,  11.26400148,  14.18063413,
        17.85302577,  22.47486282,  28.29515278,  35.6203863 ,
        44.84313437,  56.4542325 ,  71.07017994,  89.47027565,
       112.63470042, 141.7929957 , 178.50204039, 224.71991553,
         2.82916303,   3.56179547,   4.48418035,   5.64538526,
         7.10721262,   8.94797162,  11.2642115 ,  14.18087388,
        17.8532973 ,  22.47504636,  28.29549686,  35.62063269,
        44.84336567,  56.45458661,  71.0704073 ,  89.47036457,
       112.63499144, 141.79309549, 178.50286107, 224.72024147,
         2.82939786,   3.56203603,   4.48441583,   5.64562722,
         7.1074738 ,   8.948267  ,  11.26449083,  14.18113548,
        17.85369423,  22.47540214,  28.29602793,  35.62105776,
        44.84378785,  56.45501694,  71.07099943,  89.47043939,
       112.63552463, 141.79332564, 178.50282678, 224.71900994,
         2.82939671,   3.56203384,   4.48439731,   5.64

In [26]:
xip_data['NPAIRS']

array([4.47010214e+08, 6.99808086e+08, 1.09703696e+09, 1.72200606e+09,
       2.70568288e+09, 4.25699750e+09, 6.70408898e+09, 1.05425729e+10,
       1.65857187e+10, 2.61143501e+10, 4.10882998e+10, 6.46439582e+10,
       1.01625288e+11, 1.59750933e+11, 2.50851423e+11, 3.93234518e+11,
       6.15457474e+11, 9.60680794e+11, 1.49444529e+12, 2.31565519e+12,
       4.48005737e+08, 7.02168728e+08, 1.10206590e+09, 1.73153221e+09,
       2.72330912e+09, 4.28872317e+09, 6.75974266e+09, 1.06370571e+10,
       1.67437355e+10, 2.63764317e+10, 4.15195030e+10, 6.53495413e+10,
       1.02766669e+11, 1.61582713e+11, 2.53774929e+11, 3.97846839e+11,
       6.22731152e+11, 9.72111366e+11, 1.51230469e+12, 2.34351291e+12,
       4.32662745e+08, 6.80089016e+08, 1.07013850e+09, 1.68518476e+09,
       2.65503618e+09, 4.18789225e+09, 6.60987666e+09, 1.04127765e+10,
       1.64068747e+10, 2.58702878e+10, 4.07549336e+10, 6.41883347e+10,
       1.01002491e+11, 1.58888377e+11, 2.49665814e+11, 3.91527732e+11,
      